name: Deploy to next.icodewith.ai

on:
  push:
    branches:
      - dev

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.147.9
      HUGO_ENV: next 
      HUGO_ENVIRONMENT: next
      TZ: America/Los_Angeles

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Hugo
        run: |
          wget -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb
          sudo dpkg -i hugo.deb

      - name: Install Dart Sass
        run: |
          wget https://github.com/sass/dart-sass/releases/download/1.89.2/dart-sass-1.89.2-linux-x64.tar.gz
          tar -xzf dart-sass-1.89.2-linux-x64.tar.gz
          sudo cp -r dart-sass/* /usr/local/bin/

      - name: Build site
        run: hugo --environment next --minify

      - name: Deploy to Next
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DEPLOY_TOKEN }}
          external_repository: bymarcelolewin/bml-website-next
          publish_branch: gh-pages
          publish_dir: ./public
          cname: next.icodewith.ai